export const SCHEDULE = [
    {
        title: 'Main',
        view: 'weekly', // 'weekly' | 'monthly'  // leave to the front end
        start: '2020/06/26',
        end: '2020/09/19',
        dividers: [
            {
                name: 'Morning Service',
                day: 'Saturday',
                start: '10:15 AM',
                end: '12:30 PM',
                order: 1,
            },
            {
                name: 'Afternoon Service',
                start: '1:45 PM',
                end: '2:00 PM',
                day: 'Saturday',
                order: 2,
            },
            {
                name: 'Evening Service',
                start: '7:00 PM',
                end: '9:00 PM',
                day: 'Friday',
                order: 3,
            },
        ],
        events: [
            {
                time: '10:15 AM',
                day: 'Saturday',
                title: 'Usher',
                team: 'Church Council',
                order: 1,
                tasks: [
                    { date: '2020/06/27', assignee: 'Kevin Wang' },
                    { date: '2020/07/04', assignee: 'Kevin Wang' },
                    { date: '2020/07/11', assignee: 'Sun-Yu Yang' },
                    { date: '2020/07/18', assignee: 'Kevin Wang' },
                    { date: '2020/07/25', assignee: 'Sun-Yu Yang' },
                    { date: '2020/08/01', assignee: 'Kevin Wang' },
                    { date: '2020/08/08', assignee: 'Sun-Yu Yang' },
                    { date: '2020/08/15', assignee: 'Kevin Wang' },
                    { date: '2020/08/22', assignee: 'Sun-Yu Yang' },
                    { date: '2020/08/29', assignee: 'Kevin Wang' },
                    { date: '2020/09/05', assignee: 'Sun-Yu Yang' },
                    { date: '2020/09/12', assignee: 'Kevin Wang' },
                    { date: '2020/09/19', assignee: 'Sun-Yu Yang' },
                ],
            },
            {
                title: 'Hymn Leading',
                team: 'Hymn Leader',
                time: '10:45 AM',
                day: 'Saturday',
                order: 1,
                tasks: [
                    { date: '2020/06/27', assignee: 'Shenney Lin' },
                    { date: '2020/07/04', assignee: 'Chloe Lin' },
                    { date: '2020/07/11', assignee: 'Vinnie Lin' },
                    { date: '2020/07/18', assignee: 'Qianwei Liu' },
                    { date: '2020/07/25', assignee: 'Xingru Wang' },
                    { date: '2020/08/01', assignee: 'Shaun Tung' },
                    { date: '2020/08/08', assignee: 'Shenney Lin' },
                    { date: '2020/08/15', assignee: 'Chloe Lin' },
                    { date: '2020/08/22', assignee: 'Vinnie Lin' },
                    { date: '2020/08/29', assignee: 'Qianwei Liu' },
                    { date: '2020/09/05', assignee: 'Xingru Wang' },
                    { date: '2020/09/12', assignee: 'Shaun Tung' },
                    { date: '2020/09/19', assignee: 'Shenney Lin' },
                ],
            },
            {
                title: 'Piano',
                team: 'Pianist',
                time: '10:45 AM',
                day: 'Saturday',
                order: 2,
                tasks: [
                    { date: '2020/06/27', assignee: 'Shouli Tung' },
                    { date: '2020/07/04', assignee: 'Shaun Tung' },
                    { date: '2020/07/11', assignee: 'Rebecca Lin' },
                    { date: '2020/07/18', assignee: 'Shenney Lin' },
                    { date: '2020/07/25', assignee: 'Joseph Wu' },
                    { date: '2020/08/01', assignee: 'Chloe Lin' },
                    { date: '2020/08/08', assignee: 'Vinnie Lin' },
                    { date: '2020/08/15', assignee: 'Shouli Tung' },
                    { date: '2020/08/22', assignee: 'Shaun Tung' },
                    { date: '2020/08/29', assignee: 'Rebecca Lin' },
                    { date: '2020/09/05', assignee: 'Shenney Lin' },
                    { date: '2020/09/12', assignee: 'Joseph Wu' },
                    { date: '2020/09/19', assignee: 'Chloe Lin' },
                ],
            },
            {
                title: 'Sermon Speaker',
                team: 'Church Council',
                time: '11:00 AM',
                order: 1,
                day: 'Saturday',
                tasks: [
                    { date: '2020/06/27', assignee: 'Shouli Tung' },
                    { date: '2020/07/04', assignee: 'Shaun Tung' },
                    { date: '2020/07/11', assignee: 'Rebecca Lin' },
                    { date: '2020/07/18', assignee: 'Shenney Lin' },
                    { date: '2020/07/25', assignee: 'Joseph Wu' },
                    { date: '2020/08/01', assignee: 'Chloe Lin' },
                    { date: '2020/08/08', assignee: 'Vinnie Lin' },
                    { date: '2020/08/15', assignee: 'Shouli Tung' },
                    { date: '2020/08/22', assignee: 'Shaun Tung' },
                    { date: '2020/08/29', assignee: 'Rebecca Lin' },
                    { date: '2020/09/05', assignee: 'Shenney Lin' },
                    { date: '2020/09/12', assignee: 'Joseph Wu' },
                    { date: '2020/09/19', assignee: 'Chloe Lin' },
                ],
            },
            {
                title: 'Interpreter',
                team: 'Interpreter',
                time: '11:00 AM',
                order: 2,
                day: 'Saturday',
                tasks: [
                    { date: '2020/06/27', assignee: 'Joseph Wu' },
                    { date: '2020/07/04', assignee: 'Thomas Hsu' },
                    { date: '2020/07/11', assignee: 'Qianwei Liu' },
                    { date: '2020/07/18', assignee: 'Rebecca Lin' },
                    { date: '2020/07/25', assignee: 'Joseph Wu' },
                    { date: '2020/08/01', assignee: 'Thomas Hsu' },
                    { date: '2020/08/08', assignee: 'Qianwei Liu' },
                    { date: '2020/08/15', assignee: 'Rebecca Lin' },
                    { date: '2020/08/22', assignee: 'Joseph Wu' },
                    { date: '2020/08/29', assignee: 'Thomas Hsu' },
                    { date: '2020/09/05', assignee: 'Qianwei Liu' },
                    { date: '2020/09/12', assignee: 'Rebecca Lin' },
                    { date: '2020/09/19', assignee: 'Joseph Wu' },
                ],
            },
            {
                time: '12:00 PM',
                title: 'Announcer',
                day: 'Saturday',
                team: 'Church Council',
                order: 1,
                tasks: [
                    { date: '2020/06/27', assignee: 'Brenda Ong' },
                    { date: '2020/07/04', assignee: 'Kevin Wang' },
                    { date: '2020/07/11', assignee: 'Sun-Yu Yang' },
                    { date: '2020/07/18', assignee: 'Yvonne Wong' },
                    { date: '2020/07/25', assignee: 'Brenda Ong' },
                    { date: '2020/08/01', assignee: 'Kevin Wang' },
                    { date: '2020/08/08', assignee: 'Sun-Yu Yang' },
                    { date: '2020/08/15', assignee: 'Yvonne Wong' },
                    { date: '2020/08/22', assignee: 'Brenda Ong' },
                    { date: '2020/08/29', assignee: 'Kevin Wang' },
                    { date: '2020/09/05', assignee: 'Sun-Yu Yang' },
                    { date: '2020/09/12', assignee: 'Yvonne Wong' },
                    { date: '2020/09/19', assignee: 'Brenda Ong' },
                ],
            },
            {
                title: 'Grace',
                team: 'Any',
                time: '12:00 PM',
                day: 'Saturday',
                order: 2,
                tasks: [
                    { date: '2020/06/27', assignee: 'Shenney Lin' },
                    { date: '2020/07/04', assignee: 'Vinnie Lin' },
                    { date: '2020/07/11', assignee: 'Shaun Tung' },
                    { date: '2020/07/18', assignee: 'Shouli Tung' },
                    { date: '2020/07/25', assignee: 'Brenda Ong' },
                    { date: '2020/08/01', assignee: 'Kevin Wang' },
                    { date: '2020/08/08', assignee: 'Sun-Yu Yang' },
                    { date: '2020/08/15', assignee: 'Yvonne Wong' },
                    { date: '2020/08/22', assignee: 'Rebecca Lin' },
                    { date: '2020/08/29', assignee: 'Thomas Hsu' },
                    { date: '2020/09/05', assignee: 'Qianwei Liu' },
                    { date: '2020/09/12', assignee: 'Chloe Lin' },
                    { date: '2020/09/19', assignee: 'Joseph Wu' },
                ],
            },
            // {
            //     title: 'Cooking',
            //     day: 'Saturday',
            //     team: 'Any',
            //     time: '12:00 PM',
            //     order: 3,
            //     tasks: [
            //         { date: '2020/06/27', assignee: 'Team A' },
            //         { date: '2020/07/04', assignee: 'Team B' },
            //         { date: '2020/07/11', assignee: 'Team A' },
            //         { date: '2020/07/18', assignee: 'Team B' },
            //         { date: '2020/07/25', assignee: 'Team A' },
            //         { date: '2020/08/01', assignee: 'Team B' },
            //         { date: '2020/08/08', assignee: 'Team A' },
            //         { date: '2020/08/15', assignee: 'Team B' },
            //         { date: '2020/08/22', assignee: 'Team A' },
            //         { date: '2020/08/29', assignee: 'Team B' },
            //         { date: '2020/09/05', assignee: 'Team A' },
            //         { date: '2020/09/12', assignee: 'Team B' },
            //         { date: '2020/09/19', assignee: 'Team A' },
            //     ],
            // },
            {
                time: '1:45 PM',
                title: 'Hymn Leading',
                team: 'Hymn Leader',
                day: 'Saturday',
                order: 1,
                tasks: [
                    { date: '2020/06/27', assignee: 'Shenney Lin' },
                    { date: '2020/07/04', assignee: 'Chloe Lin' },
                    { date: '2020/07/11', assignee: 'Vinnie Lin' },
                    { date: '2020/07/18', assignee: 'Qianwei Liu' },
                    { date: '2020/07/25', assignee: 'Xingru Wang' },
                    { date: '2020/08/01', assignee: 'Shaun Tung' },
                    { date: '2020/08/08', assignee: 'Shenney Lin' },
                    { date: '2020/08/15', assignee: 'Chloe Lin' },
                    { date: '2020/08/22', assignee: 'Vinnie Lin' },
                    { date: '2020/08/29', assignee: 'Qianwei Liu' },
                    { date: '2020/09/05', assignee: 'Xingru Wang' },
                    { date: '2020/09/12', assignee: 'Shaun Tung' },
                    { date: '2020/09/19', assignee: 'Shenney Lin' },
                ],
            },
            {
                title: 'Piano',
                team: 'Pianist',
                day: 'Saturday',
                time: '1:45 PM',
                order: 2,
                tasks: [
                    { date: '2020/06/27', assignee: 'Shouli Tung' },
                    { date: '2020/07/04', assignee: 'Shaun Tung' },
                    { date: '2020/07/11', assignee: 'Rebecca Lin' },
                    { date: '2020/07/18', assignee: 'Shenney Lin' },
                    { date: '2020/07/25', assignee: 'Joseph Wu' },
                    { date: '2020/08/01', assignee: 'Chloe Lin' },
                    { date: '2020/08/08', assignee: 'Vinnie Lin' },
                    { date: '2020/08/15', assignee: 'Shouli Tung' },
                    { date: '2020/08/22', assignee: 'Shaun Tung' },
                    { date: '2020/08/29', assignee: 'Rebecca Lin' },
                    { date: '2020/09/05', assignee: 'Shenney Lin' },
                    { date: '2020/09/12', assignee: 'Joseph Wu' },
                    { date: '2020/09/19', assignee: 'Chloe Lin' },
                ],
            },
            {
                title: 'Sermon Speaker',
                team: 'Church Council',
                day: 'Saturday',
                time: '2:00 PM',
                order: 1,
                tasks: [
                    { date: '2020/06/27', assignee: 'Shouli Tung' },
                    { date: '2020/07/04', assignee: 'Shaun Tung' },
                    { date: '2020/07/11', assignee: 'Rebecca Lin' },
                    { date: '2020/07/18', assignee: 'Shenney Lin' },
                    { date: '2020/07/25', assignee: 'Joseph Wu' },
                    { date: '2020/08/01', assignee: 'Chloe Lin' },
                    { date: '2020/08/08', assignee: 'Vinnie Lin' },
                    { date: '2020/08/15', assignee: 'Shouli Tung' },
                    { date: '2020/08/22', assignee: 'Shaun Tung' },
                    { date: '2020/08/29', assignee: 'Rebecca Lin' },
                    { date: '2020/09/05', assignee: 'Shenney Lin' },
                    { date: '2020/09/12', assignee: 'Joseph Wu' },
                    { date: '2020/09/19', assignee: 'Chloe Lin' },
                ],
            },
            {
                title: 'Interpreter',
                team: 'Interpreter',
                day: 'Saturday',
                order: 2,
                time: '2:00 PM',
                tasks: [
                    { date: '2020/06/27', assignee: 'Joseph Wu' },
                    { date: '2020/07/04', assignee: 'Thomas Hsu' },
                    { date: '2020/07/11', assignee: 'Qianwei Liu' },
                    { date: '2020/07/18', assignee: 'Rebecca Lin' },
                    { date: '2020/07/25', assignee: 'Joseph Wu' },
                    { date: '2020/08/01', assignee: 'Thomas Hsu' },
                    { date: '2020/08/08', assignee: 'Qianwei Liu' },
                    { date: '2020/08/15', assignee: 'Rebecca Lin' },
                    { date: '2020/08/22', assignee: 'Joseph Wu' },
                    { date: '2020/08/29', assignee: 'Thomas Hsu' },
                    { date: '2020/09/05', assignee: 'Qianwei Liu' },
                    { date: '2020/09/12', assignee: 'Rebecca Lin' },
                    { date: '2020/09/19', assignee: 'Joseph Wu' },
                ],
            },
            {
                title: 'Usher',
                team: 'Church Council',
                time: '7:00 PM',
                day: 'Friday',
                order: 1,
                tasks: [
                    { date: '2020/06/26', assignee: 'Kevin Wang' },
                    { date: '2020/07/03', assignee: 'Kevin Wang' },
                    { date: '2020/07/10', assignee: 'Sun-Yu Yang' },
                    { date: '2020/07/17', assignee: 'Kevin Wang' },
                    { date: '2020/07/24', assignee: 'Sun-Yu Yang' },
                    { date: '2020/07/31', assignee: 'Kevin Wang' },
                    { date: '2020/08/07', assignee: 'Sun-Yu Yang' },
                    { date: '2020/08/14', assignee: 'Kevin Wang' },
                    { date: '2020/08/21', assignee: 'Sun-Yu Yang' },
                    { date: '2020/08/28', assignee: 'Kevin Wang' },
                    { date: '2020/09/04', assignee: 'Sun-Yu Yang' },
                    { date: '2020/09/11', assignee: 'Kevin Wang' },
                    { date: '2020/09/18', assignee: 'Sun-Yu Yang' },
                ],
            },
            {
                title: 'Hymn Leading',
                team: 'Hymn Leader',
                time: '7:45 PM',
                day: 'Friday',
                order: 1,
                tasks: [
                    { date: '2020/06/26', assignee: 'Shenney Lin' },
                    { date: '2020/07/03', assignee: 'Chloe Lin' },
                    { date: '2020/07/10', assignee: 'Vinnie Lin' },
                    { date: '2020/07/17', assignee: 'Qianwei Liu' },
                    { date: '2020/07/24', assignee: 'Xingru Wang' },
                    { date: '2020/07/31', assignee: 'Shaun Tung' },
                    { date: '2020/08/07', assignee: 'Shenney Lin' },
                    { date: '2020/08/14', assignee: 'Chloe Lin' },
                    { date: '2020/08/21', assignee: 'Vinnie Lin' },
                    { date: '2020/08/28', assignee: 'Qianwei Liu' },
                    { date: '2020/09/04', assignee: 'Xingru Wang' },
                    { date: '2020/09/11', assignee: 'Shaun Tung' },
                    { date: '2020/09/18', assignee: 'Shenney Lin' },
                ],
            },
            {
                title: 'Piano',
                team: 'Pianist',
                time: '7:45 PM',
                day: 'Friday',
                order: 2,
                tasks: [
                    { date: '2020/06/26', assignee: 'Shouli Tung' },
                    { date: '2020/07/03', assignee: 'Shaun Tung' },
                    { date: '2020/07/10', assignee: 'Rebecca Lin' },
                    { date: '2020/07/17', assignee: 'Shenney Lin' },
                    { date: '2020/07/24', assignee: 'Joseph Wu' },
                    { date: '2020/07/31', assignee: 'Chloe Lin' },
                    { date: '2020/08/07', assignee: 'Vinnie Lin' },
                    { date: '2020/08/14', assignee: 'Shouli Tung' },
                    { date: '2020/08/21', assignee: 'Shaun Tung' },
                    { date: '2020/08/28', assignee: 'Rebecca Lin' },
                    { date: '2020/09/04', assignee: 'Shenney Lin' },
                    { date: '2020/09/11', assignee: 'Joseph Wu' },
                    { date: '2020/09/18', assignee: 'Chloe Lin' },
                ],
            },
            {
                title: 'Sermon Speaker',
                team: 'Church Council',
                time: '8:00 PM',
                day: 'Friday',
                order: 1,
                tasks: [
                    { date: '2020/06/26', assignee: 'Shouli Tung' },
                    { date: '2020/07/03', assignee: 'Shaun Tung' },
                    { date: '2020/07/10', assignee: 'Rebecca Lin' },
                    { date: '2020/07/17', assignee: 'Shenney Lin' },
                    { date: '2020/07/24', assignee: 'Joseph Wu' },
                    { date: '2020/07/31', assignee: 'Chloe Lin' },
                    { date: '2020/08/07', assignee: 'Vinnie Lin' },
                    { date: '2020/08/14', assignee: 'Shouli Tung' },
                    { date: '2020/08/21', assignee: 'Shaun Tung' },
                    { date: '2020/08/28', assignee: 'Rebecca Lin' },
                    { date: '2020/09/04', assignee: 'Shenney Lin' },
                    { date: '2020/09/11', assignee: 'Joseph Wu' },
                    { date: '2020/09/18', assignee: 'Chloe Lin' },
                ],
            },
            {
                title: 'Interpreter',
                team: 'Interpreter',
                time: '8:00 PM',
                day: 'Friday',
                order: 2,
                tasks: [
                    { date: '2020/06/26', assignee: 'Joseph Wu' },
                    { date: '2020/07/03', assignee: 'Thomas Hsu' },
                    { date: '2020/07/10', assignee: 'Qianwei Liu' },
                    { date: '2020/07/17', assignee: 'Rebecca Lin' },
                    { date: '2020/07/24', assignee: 'Joseph Wu' },
                    { date: '2020/07/31', assignee: 'Thomas Hsu' },
                    { date: '2020/08/07', assignee: 'Qianwei Liu' },
                    { date: '2020/08/14', assignee: 'Rebecca Lin' },
                    { date: '2020/08/21', assignee: 'Joseph Wu' },
                    { date: '2020/08/28', assignee: 'Thomas Hsu' },
                    { date: '2020/09/04', assignee: 'Qianwei Liu' },
                    { date: '2020/09/11', assignee: 'Rebecca Lin' },
                    { date: '2020/09/18', assignee: 'Joseph Wu' },
                ],
            },
        ],
        specificEvents: [],
    },
    // {
    //     title: 'Religious Education',
    //     view: 'monthly',
    //     start: '2020/09/19',
    //     end: '2020/09/19',
    //     dividers: [{ name: null, day: 'Saturday', start: '11:00 AM', end: '1:30 PM' }],
    //     events: [
    //         {
    //             title: 'E1 Teacher',
    //             team: 'E1 Teacher',
    //             order: 1,
    //             day: 'Saturday',
    //             time: '11:00 AM',
    //             tasks: [
    //                 {
    //                     date: '2020/09/19',
    //                     assignee: 'Joseph Wu',
    //                 },
    //             ],
    //         },
    //         {
    //             title: 'Kindegarten Teacher',
    //             team: 'Kindegarten Teacher',
    //             time: '11:00 AM',
    //             day: 'Saturday',
    //             order: 1,
    //             tasks: [{ date: '2020/09/19', assignee: 'Yvonne Wong' }],
    //         },
    //         {
    //             title: 'E2 Teacher',
    //             team: 'E2 Teacher',
    //             time: '1:30 PM',
    //             day: 'Saturday',
    //             order: 1,
    //             tasks: [{ date: '2020/09/19', assignee: 'Joannie Yeh' }],
    //         },
    //         {
    //             team: 'J2 Teacher',
    //             title: 'J2 Teacher',
    //             order: 2,
    //             day: 'Saturday',
    //             time: '1:30 PM',
    //             tasks: [{ date: '2020/09/19', assignee: 'Sun-Yu Yang' }],
    //         },
    //     ],
    // },
];
