/* eslint-disable @typescript-eslint/camelcase */
const Kevin_Wang = 'Kevin Wang';
const Sun_Yu_Yang = 'Sun-Yu Yang';
const Shenney_Lin = 'Shenney Lin';
const Xingru_Wang = 'Xingru Wang';
const Shaun_Tung = 'Shaun Tung';
const Rebecca_Lin = 'Rebecca Lin';
const Chloe_Lin = 'Chloe Lin';
const Vinnie_Lin = 'Vinnie Lin';
const Qianwei_Liu = 'Qianwei Liu';
const Shouli_Tung = 'Shouli Tung';
const Joseph_Wu = 'Joseph Wu';
const Brenda_Ong = 'Brenda Ong';
const Thomas_Hsu = 'Thomas Hsu';
const Yvonne_Wong = 'Yvonne Wong';

export const SCHEDULE = [
  {
    title: 'Main',
    view: 'weekly', // 'weekly' | 'monthly'  // leave to the front end
    start: '2020/06/26',
    end: '2020/09/19',
    roleId: 0,
    services: [
      {
        name: 'Morning Service',
        day: 'Saturday',
        start: '10:15 AM',
        end: '12:30 PM',
        order: 1,
        events: [
          {
            time: '10:15 AM',
            day: 'Saturday',
            title: 'Usher',
            team: 'Church Council',
            order: 1,
            tasks: [
              { date: '2020/06/27', assignee: Kevin_Wang },
              { date: '2020/07/04', assignee: Kevin_Wang },
              { date: '2020/07/11', assignee: Sun_Yu_Yang },
              { date: '2020/07/18', assignee: Kevin_Wang },
              { date: '2020/07/25', assignee: Sun_Yu_Yang },
              { date: '2020/08/01', assignee: Kevin_Wang },
              { date: '2020/08/08', assignee: Sun_Yu_Yang },
              { date: '2020/08/15', assignee: Kevin_Wang },
              { date: '2020/08/22', assignee: Sun_Yu_Yang },
              { date: '2020/08/29', assignee: Kevin_Wang },
              { date: '2020/09/05', assignee: Sun_Yu_Yang },
              { date: '2020/09/12', assignee: Kevin_Wang },
              { date: '2020/09/19', assignee: Sun_Yu_Yang },
            ],
          },
          {
            title: 'Hymn Leading',
            team: 'Hymn Leader',
            time: '10:45 AM',
            day: 'Saturday',
            order: 1,
            tasks: [
              { date: '2020/06/27', assignee: Shenney_Lin },
              { date: '2020/07/04', assignee: Chloe_Lin },
              { date: '2020/07/11', assignee: Vinnie_Lin },
              { date: '2020/07/18', assignee: Qianwei_Liu },
              { date: '2020/07/25', assignee: Xingru_Wang },
              { date: '2020/08/01', assignee: Shaun_Tung },
              { date: '2020/08/08', assignee: Shenney_Lin },
              { date: '2020/08/15', assignee: Chloe_Lin },
              { date: '2020/08/22', assignee: Vinnie_Lin },
              { date: '2020/08/29', assignee: Qianwei_Liu },
              { date: '2020/09/05', assignee: Xingru_Wang },
              { date: '2020/09/12', assignee: Shaun_Tung },
              { date: '2020/09/19', assignee: Shenney_Lin },
            ],
          },
          {
            title: 'Piano',
            team: 'Pianist',
            time: '10:45 AM',
            day: 'Saturday',
            order: 2,
            tasks: [
              { date: '2020/06/27', assignee: Shouli_Tung },
              { date: '2020/07/04', assignee: Shaun_Tung },
              { date: '2020/07/11', assignee: Rebecca_Lin },
              { date: '2020/07/18', assignee: Shenney_Lin },
              { date: '2020/07/25', assignee: Joseph_Wu },
              { date: '2020/08/01', assignee: Chloe_Lin },
              { date: '2020/08/08', assignee: Vinnie_Lin },
              { date: '2020/08/15', assignee: Shouli_Tung },
              { date: '2020/08/22', assignee: Shaun_Tung },
              { date: '2020/08/29', assignee: Rebecca_Lin },
              { date: '2020/09/05', assignee: Shenney_Lin },
              { date: '2020/09/12', assignee: Joseph_Wu },
              { date: '2020/09/19', assignee: Chloe_Lin },
            ],
          },
          {
            title: 'Sermon Speaker',
            team: 'Church Council',
            time: '11:00 AM',
            order: 1,
            day: 'Saturday',
            tasks: [
              { date: '2020/06/27', assignee: Sun_Yu_Yang },
              { date: '2020/07/04', assignee: Sun_Yu_Yang },
              { date: '2020/07/11', assignee: Kevin_Wang },
              { date: '2020/07/18', assignee: Sun_Yu_Yang },
              { date: '2020/07/25', assignee: Kevin_Wang },
              { date: '2020/08/01', assignee: Sun_Yu_Yang },
              { date: '2020/08/08', assignee: Kevin_Wang },
              { date: '2020/08/15', assignee: Sun_Yu_Yang },
              { date: '2020/08/22', assignee: Kevin_Wang },
              { date: '2020/08/29', assignee: Sun_Yu_Yang },
              { date: '2020/09/05', assignee: Kevin_Wang },
              { date: '2020/09/12', assignee: Sun_Yu_Yang },
              { date: '2020/09/19', assignee: Kevin_Wang },
            ],
          },
          {
            title: 'Interpreter',
            team: 'Interpreter',
            time: '11:00 AM',
            order: 2,
            day: 'Saturday',
            tasks: [
              { date: '2020/06/27', assignee: Joseph_Wu },
              { date: '2020/07/04', assignee: Thomas_Hsu },
              { date: '2020/07/11', assignee: Qianwei_Liu },
              { date: '2020/07/18', assignee: Rebecca_Lin },
              { date: '2020/07/25', assignee: Joseph_Wu },
              { date: '2020/08/01', assignee: Thomas_Hsu },
              { date: '2020/08/08', assignee: Qianwei_Liu },
              { date: '2020/08/15', assignee: Rebecca_Lin },
              { date: '2020/08/22', assignee: Joseph_Wu },
              { date: '2020/08/29', assignee: Thomas_Hsu },
              { date: '2020/09/05', assignee: Qianwei_Liu },
              { date: '2020/09/12', assignee: Rebecca_Lin },
              { date: '2020/09/19', assignee: Joseph_Wu },
            ],
          },
          {
            time: '12:00 PM',
            title: 'Announcer',
            day: 'Saturday',
            team: 'Church Council',
            order: 1,
            tasks: [
              { date: '2020/06/27', assignee: Brenda_Ong },
              { date: '2020/07/04', assignee: Kevin_Wang },
              { date: '2020/07/11', assignee: Sun_Yu_Yang },
              { date: '2020/07/18', assignee: Yvonne_Wong },
              { date: '2020/07/25', assignee: Brenda_Ong },
              { date: '2020/08/01', assignee: Kevin_Wang },
              { date: '2020/08/08', assignee: Sun_Yu_Yang },
              { date: '2020/08/15', assignee: Yvonne_Wong },
              { date: '2020/08/22', assignee: Brenda_Ong },
              { date: '2020/08/29', assignee: Kevin_Wang },
              { date: '2020/09/05', assignee: Sun_Yu_Yang },
              { date: '2020/09/12', assignee: Yvonne_Wong },
              { date: '2020/09/19', assignee: Brenda_Ong },
            ],
          },
          {
            title: 'Grace',
            team: 'Any',
            time: '12:00 PM',
            day: 'Saturday',
            order: 2,
            tasks: [
              { date: '2020/06/27', assignee: Shenney_Lin },
              { date: '2020/07/04', assignee: Vinnie_Lin },
              { date: '2020/07/11', assignee: Shaun_Tung },
              { date: '2020/07/18', assignee: Shouli_Tung },
              { date: '2020/07/25', assignee: Brenda_Ong },
              { date: '2020/08/01', assignee: Kevin_Wang },
              { date: '2020/08/08', assignee: Sun_Yu_Yang },
              { date: '2020/08/15', assignee: Yvonne_Wong },
              { date: '2020/08/22', assignee: Rebecca_Lin },
              { date: '2020/08/29', assignee: Thomas_Hsu },
              { date: '2020/09/05', assignee: Qianwei_Liu },
              { date: '2020/09/12', assignee: Chloe_Lin },
              { date: '2020/09/19', assignee: Joseph_Wu },
            ],
          },
        ],
      },
      {
        name: 'Afternoon Service',
        start: '1:45 PM',
        end: '2:00 PM',
        day: 'Saturday',
        order: 2,
        events: [
          {
            time: '1:45 PM',
            title: 'Hymn Leading',
            team: 'Hymn Leader',
            day: 'Saturday',
            order: 1,
            tasks: [
              { date: '2020/06/27', assignee: Shenney_Lin },
              { date: '2020/07/04', assignee: Chloe_Lin },
              { date: '2020/07/11', assignee: Vinnie_Lin },
              { date: '2020/07/18', assignee: Qianwei_Liu },
              { date: '2020/07/25', assignee: Xingru_Wang },
              { date: '2020/08/01', assignee: Shaun_Tung },
              { date: '2020/08/08', assignee: Shenney_Lin },
              { date: '2020/08/15', assignee: Chloe_Lin },
              { date: '2020/08/22', assignee: Vinnie_Lin },
              { date: '2020/08/29', assignee: Qianwei_Liu },
              { date: '2020/09/05', assignee: Xingru_Wang },
              { date: '2020/09/12', assignee: Shaun_Tung },
              { date: '2020/09/19', assignee: Shenney_Lin },
            ],
          },
          {
            title: 'Piano',
            team: 'Pianist',
            day: 'Saturday',
            time: '1:45 PM',
            order: 2,
            tasks: [
              { date: '2020/06/27', assignee: Shouli_Tung },
              { date: '2020/07/04', assignee: Shaun_Tung },
              { date: '2020/07/11', assignee: Rebecca_Lin },
              { date: '2020/07/18', assignee: Shenney_Lin },
              { date: '2020/07/25', assignee: Joseph_Wu },
              { date: '2020/08/01', assignee: Chloe_Lin },
              { date: '2020/08/08', assignee: Vinnie_Lin },
              { date: '2020/08/15', assignee: Shouli_Tung },
              { date: '2020/08/22', assignee: Shaun_Tung },
              { date: '2020/08/29', assignee: Rebecca_Lin },
              { date: '2020/09/05', assignee: Shenney_Lin },
              { date: '2020/09/12', assignee: Joseph_Wu },
              { date: '2020/09/19', assignee: Chloe_Lin },
            ],
          },
          {
            title: 'Sermon Speaker',
            team: 'Church Council',
            day: 'Saturday',
            time: '2:00 PM',
            order: 1,
            tasks: [
              { date: '2020/06/27', assignee: Sun_Yu_Yang },
              { date: '2020/07/04', assignee: Sun_Yu_Yang },
              { date: '2020/07/11', assignee: Kevin_Wang },
              { date: '2020/07/18', assignee: Sun_Yu_Yang },
              { date: '2020/07/25', assignee: Kevin_Wang },
              { date: '2020/08/01', assignee: Sun_Yu_Yang },
              { date: '2020/08/08', assignee: Kevin_Wang },
              { date: '2020/08/15', assignee: Sun_Yu_Yang },
              { date: '2020/08/22', assignee: Kevin_Wang },
              { date: '2020/08/29', assignee: Sun_Yu_Yang },
              { date: '2020/09/05', assignee: Kevin_Wang },
              { date: '2020/09/12', assignee: Sun_Yu_Yang },
              { date: '2020/09/19', assignee: Kevin_Wang },
            ],
          },
          {
            title: 'Interpreter',
            team: 'Interpreter',
            day: 'Saturday',
            order: 2,
            time: '2:00 PM',
            tasks: [
              { date: '2020/06/27', assignee: Joseph_Wu },
              { date: '2020/07/04', assignee: Thomas_Hsu },
              { date: '2020/07/11', assignee: Qianwei_Liu },
              { date: '2020/07/18', assignee: Rebecca_Lin },
              { date: '2020/07/25', assignee: Joseph_Wu },
              { date: '2020/08/01', assignee: Thomas_Hsu },
              { date: '2020/08/08', assignee: Qianwei_Liu },
              { date: '2020/08/15', assignee: Rebecca_Lin },
              { date: '2020/08/22', assignee: Joseph_Wu },
              { date: '2020/08/29', assignee: Thomas_Hsu },
              { date: '2020/09/05', assignee: Qianwei_Liu },
              { date: '2020/09/12', assignee: Rebecca_Lin },
              { date: '2020/09/19', assignee: Joseph_Wu },
            ],
          },
        ],
      },
      {
        name: 'Evening Service',
        start: '7:00 PM',
        end: '9:00 PM',
        day: 'Friday',
        order: 3,
        events: [
          {
            title: 'Usher',
            team: 'Church Council',
            time: '7:00 PM',
            day: 'Friday',
            order: 1,
            tasks: [
              { date: '2020/06/26', assignee: Kevin_Wang },
              { date: '2020/07/03', assignee: Kevin_Wang },
              { date: '2020/07/10', assignee: Sun_Yu_Yang },
              { date: '2020/07/17', assignee: Kevin_Wang },
              { date: '2020/07/24', assignee: Sun_Yu_Yang },
              { date: '2020/07/31', assignee: Kevin_Wang },
              { date: '2020/08/07', assignee: Sun_Yu_Yang },
              { date: '2020/08/14', assignee: Kevin_Wang },
              { date: '2020/08/21', assignee: Sun_Yu_Yang },
              { date: '2020/08/28', assignee: Kevin_Wang },
              { date: '2020/09/04', assignee: Sun_Yu_Yang },
              { date: '2020/09/11', assignee: Kevin_Wang },
              { date: '2020/09/18', assignee: Sun_Yu_Yang },
            ],
          },
          {
            title: 'Hymn Leading',
            team: 'Hymn Leader',
            time: '7:45 PM',
            day: 'Friday',
            order: 1,
            tasks: [
              { date: '2020/06/26', assignee: Shenney_Lin },
              { date: '2020/07/03', assignee: Chloe_Lin },
              { date: '2020/07/10', assignee: Vinnie_Lin },
              { date: '2020/07/17', assignee: Qianwei_Liu },
              { date: '2020/07/24', assignee: Xingru_Wang },
              { date: '2020/07/31', assignee: Shaun_Tung },
              { date: '2020/08/07', assignee: Shenney_Lin },
              { date: '2020/08/14', assignee: Chloe_Lin },
              { date: '2020/08/21', assignee: Vinnie_Lin },
              { date: '2020/08/28', assignee: Qianwei_Liu },
              { date: '2020/09/04', assignee: Xingru_Wang },
              { date: '2020/09/11', assignee: Shaun_Tung },
              { date: '2020/09/18', assignee: Shenney_Lin },
            ],
          },
          {
            title: 'Piano',
            team: 'Pianist',
            time: '7:45 PM',
            day: 'Friday',
            order: 2,
            tasks: [
              { date: '2020/06/26', assignee: Shouli_Tung },
              { date: '2020/07/03', assignee: Shaun_Tung },
              { date: '2020/07/10', assignee: Rebecca_Lin },
              { date: '2020/07/17', assignee: Shenney_Lin },
              { date: '2020/07/24', assignee: Joseph_Wu },
              { date: '2020/07/31', assignee: Chloe_Lin },
              { date: '2020/08/07', assignee: Vinnie_Lin },
              { date: '2020/08/14', assignee: Shouli_Tung },
              { date: '2020/08/21', assignee: Shaun_Tung },
              { date: '2020/08/28', assignee: Rebecca_Lin },
              { date: '2020/09/04', assignee: Shenney_Lin },
              { date: '2020/09/11', assignee: Joseph_Wu },
              { date: '2020/09/18', assignee: Chloe_Lin },
            ],
          },
          {
            title: 'Sermon Speaker',
            team: 'Church Council',
            time: '8:00 PM',
            day: 'Friday',
            order: 1,
            tasks: [
              { date: '2020/06/26', assignee: Sun_Yu_Yang },
              { date: '2020/07/03', assignee: Sun_Yu_Yang },
              { date: '2020/07/10', assignee: Kevin_Wang },
              { date: '2020/07/17', assignee: Sun_Yu_Yang },
              { date: '2020/07/24', assignee: Kevin_Wang },
              { date: '2020/07/31', assignee: Sun_Yu_Yang },
              { date: '2020/08/07', assignee: Kevin_Wang },
              { date: '2020/08/14', assignee: Sun_Yu_Yang },
              { date: '2020/08/21', assignee: Kevin_Wang },
              { date: '2020/08/28', assignee: Sun_Yu_Yang },
              { date: '2020/09/04', assignee: Kevin_Wang },
              { date: '2020/09/11', assignee: Sun_Yu_Yang },
              { date: '2020/09/18', assignee: Kevin_Wang },
            ],
          },
          {
            title: 'Interpreter',
            team: 'Interpreter',
            time: '8:00 PM',
            day: 'Friday',
            order: 2,
            tasks: [
              { date: '2020/06/26', assignee: Joseph_Wu },
              { date: '2020/07/03', assignee: Thomas_Hsu },
              { date: '2020/07/10', assignee: Qianwei_Liu },
              { date: '2020/07/17', assignee: Rebecca_Lin },
              { date: '2020/07/24', assignee: Joseph_Wu },
              { date: '2020/07/31', assignee: Thomas_Hsu },
              { date: '2020/08/07', assignee: Qianwei_Liu },
              { date: '2020/08/14', assignee: Rebecca_Lin },
              { date: '2020/08/21', assignee: Joseph_Wu },
              { date: '2020/08/28', assignee: Thomas_Hsu },
              { date: '2020/09/04', assignee: Qianwei_Liu },
              { date: '2020/09/11', assignee: Rebecca_Lin },
              { date: '2020/09/18', assignee: Joseph_Wu },
            ],
          },
        ],
      },
    ],
  },
  // {
  //     title: 'Religious Education',
  //     view: 'monthly',
  //     start: '2020/09/19',
  //     end: '2020/09/19',
  //     roleId: 8,
  //     services: [
  //         {
  //             name: null,
  //             day: 'Saturday',
  //             start: '11:00 AM',
  //             end: '1:30 PM',
  //             events: [
  //                 {
  //                     title: 'E1 Teacher',
  //                     team: 'E1 Teacher',
  //                     order: 1,
  //                     day: 'Saturday',
  //                     time: '11:00 AM',
  //                     tasks: [
  //                         {
  //                             date: '2020/09/19',
  //                             assignee: Joseph_Wu,
  //                         },
  //                     ],
  //                 },
  //                 {
  //                     title: 'Kindegarten Teacher',
  //                     team: 'Kindegarten Teacher',
  //                     time: '11:00 AM',
  //                     day: 'Saturday',
  //                     order: 1,
  //                     tasks: [{ date: '2020/09/19', assignee: Yvonne_Wong }],
  //                 },
  //                 {
  //                     title: 'E2 Teacher',
  //                     team: 'E2 Teacher',
  //                     time: '1:30 PM',
  //                     day: 'Saturday',
  //                     order: 1,
  //                     tasks: [{ date: '2020/09/19', assignee: 'Joannie Yeh' }],
  //                 },
  //                 {
  //                     team: 'J2 Teacher',
  //                     title: 'J2 Teacher',
  //                     order: 2,
  //                     day: 'Saturday',
  //                     time: '1:30 PM',
  //                     tasks: [{ date: '2020/09/19', assignee: Sun_Yu_Yang }],
  //                 },
  //             ],
  //         },
  //     ],
  // },
];
