// eslint-disable-next-line import/prefer-default-export
export const events = [
    {
        time: '10:15 AM',
        tasks: [
            {
                title: 'Usher',
                role: 'Church Council',
                data: [
                    { date: '2020/06/27', assignee: 'Kevin Wang' },
                    { date: '2020/07/04', assignee: 'Kevin Wang' },
                    { date: '2020/07/11', assignee: 'Sun-Yu Yang' },
                    { date: '2020/07/18', assignee: 'Kevin Wang' },
                    { date: '2020/07/25', assignee: 'Sun-Yu Yang' },
                    { date: '2020/08/01', assignee: 'Kevin Wang' },
                    { date: '2020/08/08', assignee: 'Sun-Yu Yang' },
                    { date: '2020/08/15', assignee: 'Kevin Wang' },
                    { date: '2020/08/22', assignee: 'Sun-Yu Yang' },
                    { date: '2020/08/29', assignee: 'Kevin Wang' },
                    { date: '2020/09/05', assignee: 'Sun-Yu Yang' },
                    { date: '2020/09/12', assignee: 'Kevin Wang' },
                    { date: '2020/09/19', assignee: 'Sun-Yu Yang' },
                ],
            },
        ],
    },
    {
        time: '10:45 AM',
        tasks: [
            {
                title: 'Hymn Leading',
                role: 'Hymn Leader',
                data: [
                    { date: '2020/06/27', assignee: 'Shenney Lin' },
                    { date: '2020/07/04', assignee: 'Chloe Lin' },
                    { date: '2020/07/11', assignee: 'Vinnie Lin' },
                    { date: '2020/07/18', assignee: 'Qianwei Liu' },
                    { date: '2020/07/25', assignee: 'Xingru Wang' },
                    { date: '2020/08/01', assignee: 'Shaun Tung' },
                    { date: '2020/08/08', assignee: 'Shenney Lin' },
                    { date: '2020/08/15', assignee: 'Chloe Lin' },
                    { date: '2020/08/22', assignee: 'Vinnie Lin' },
                    { date: '2020/08/29', assignee: 'Qianwei Liu' },
                    { date: '2020/09/05', assignee: 'Xingru Wang' },
                    { date: '2020/09/12', assignee: 'Shaun Tung' },
                    { date: '2020/09/19', assignee: 'Shenney Lin' },
                ],
            },
            {
                title: 'Piano',
                role: 'Pianist',
                data: [
                    { date: '2020/06/27', assignee: 'Shouli Tung' },
                    { date: '2020/07/04', assignee: 'Shaun Tung' },
                    { date: '2020/07/11', assignee: 'Rebecca Lin' },
                    { date: '2020/07/18', assignee: 'Shenney Lin' },
                    { date: '2020/07/25', assignee: 'Joseph Wu' },
                    { date: '2020/08/01', assignee: 'Chloe Lin' },
                    { date: '2020/08/08', assignee: 'Vinnie Lin' },
                    { date: '2020/08/15', assignee: 'Shouli Tung' },
                    { date: '2020/08/22', assignee: 'Shaun Tung' },
                    { date: '2020/08/29', assignee: 'Rebecca Lin' },
                    { date: '2020/09/05', assignee: 'Shenney Lin' },
                    { date: '2020/09/12', assignee: 'Joseph Wu' },
                    { date: '2020/09/19', assignee: 'Chloe Lin' },
                ],
            },
        ],
    },
    {
        time: '11:00 AM',
        tasks: [
            {
                title: 'Sermon Speaker',
                role: 'Church Council',
                data: [
                    { date: '2020/06/27', assignee: 'Shouli Tung' },
                    { date: '2020/07/04', assignee: 'Shaun Tung' },
                    { date: '2020/07/11', assignee: 'Rebecca Lin' },
                    { date: '2020/07/18', assignee: 'Shenney Lin' },
                    { date: '2020/07/25', assignee: 'Joseph Wu' },
                    { date: '2020/08/01', assignee: 'Chloe Lin' },
                    { date: '2020/08/08', assignee: 'Vinnie Lin' },
                    { date: '2020/08/15', assignee: 'Shouli Tung' },
                    { date: '2020/08/22', assignee: 'Shaun Tung' },
                    { date: '2020/08/29', assignee: 'Rebecca Lin' },
                    { date: '2020/09/05', assignee: 'Shenney Lin' },
                    { date: '2020/09/12', assignee: 'Joseph Wu' },
                    { date: '2020/09/19', assignee: 'Chloe Lin' },
                ],
            },
            {
                title: 'Interpreter',
                role: 'Interpreter',
                data: [
                    { date: '2020/06/27', assignee: 'Joseph Wu' },
                    { date: '2020/07/04', assignee: 'Thomas Hsu' },
                    { date: '2020/07/11', assignee: 'Qianwei Liu' },
                    { date: '2020/07/18', assignee: 'Rebecca Lin' },
                    { date: '2020/07/25', assignee: 'Joseph Wu' },
                    { date: '2020/08/01', assignee: 'Thomas Hsu' },
                    { date: '2020/08/08', assignee: 'Qianwei Liu' },
                    { date: '2020/08/15', assignee: 'Rebecca Lin' },
                    { date: '2020/08/22', assignee: 'Joseph Wu' },
                    { date: '2020/08/29', assignee: 'Thomas Hsu' },
                    { date: '2020/09/05', assignee: 'Qianwei Liu' },
                    { date: '2020/09/12', assignee: 'Rebecca Lin' },
                    { date: '2020/09/19', assignee: 'Joseph Wu' },
                ],
            },
        ],
    },
    {
        time: '12:00 PM',
        tasks: [
            {
                title: 'Announcer',
                role: 'Church Council',
                data: [
                    { date: '2020/06/27', assignee: 'Brenda Ong' },
                    { date: '2020/07/04', assignee: 'Kevin Wang' },
                    { date: '2020/07/11', assignee: 'Sun-Yu Yang' },
                    { date: '2020/07/18', assignee: 'Yvonne Wong' },
                    { date: '2020/07/25', assignee: 'Brenda Ong' },
                    { date: '2020/08/01', assignee: 'Kevin Wang' },
                    { date: '2020/08/08', assignee: 'Sun-Yu Yang' },
                    { date: '2020/08/15', assignee: 'Yvonne Wong' },
                    { date: '2020/08/22', assignee: 'Brenda Ong' },
                    { date: '2020/08/29', assignee: 'Kevin Wang' },
                    { date: '2020/09/05', assignee: 'Sun-Yu Yang' },
                    { date: '2020/09/12', assignee: 'Yvonne Wong' },
                    { date: '2020/09/19', assignee: 'Brenda Ong' },
                ],
            },
            {
                title: 'Grace',
                role: 'any',
                data: [
                    { date: '2020/06/27', assignee: 'Shenney Lin' },
                    { date: '2020/07/04', assignee: 'Vinnie Lin' },
                    { date: '2020/07/11', assignee: 'Shaun Tung' },
                    { date: '2020/07/18', assignee: 'Shouli Tung' },
                    { date: '2020/07/25', assignee: 'Brenda Ong' },
                    { date: '2020/08/01', assignee: 'Kevin Wang' },
                    { date: '2020/08/08', assignee: 'Sun-Yu Yang' },
                    { date: '2020/08/15', assignee: 'Yvonne Wong' },
                    { date: '2020/08/22', assignee: 'Rebecca Lin' },
                    { date: '2020/08/29', assignee: 'Thomas Hsu' },
                    { date: '2020/09/05', assignee: 'Qianwei Liu' },
                    { date: '2020/09/12', assignee: 'Chloe Lin' },
                    { date: '2020/09/19', assignee: 'Joseph Wu' },
                ],
            },
            {
                title: 'Cooking',
                data: [
                    { date: '2020/06/27', assignee: 'Team A' },
                    { date: '2020/07/04', assignee: 'Team B' },
                    { date: '2020/07/11', assignee: 'Team A' },
                    { date: '2020/07/18', assignee: 'Team B' },
                    { date: '2020/07/25', assignee: 'Team A' },
                    { date: '2020/08/01', assignee: 'Team B' },
                    { date: '2020/08/08', assignee: 'Team A' },
                    { date: '2020/08/15', assignee: 'Team B' },
                    { date: '2020/08/22', assignee: 'Team A' },
                    { date: '2020/08/29', assignee: 'Team B' },
                    { date: '2020/09/05', assignee: 'Team A' },
                    { date: '2020/09/12', assignee: 'Team B' },
                    { date: '2020/09/19', assignee: 'Team A' },
                ],
            },
        ],
    },
    {
        time: '1:45 PM',
        tasks: [
            {
                title: 'Hymn Leading',
                role: 'Hymn Leader',
                data: [
                    { date: '2020/06/27', assignee: 'Shenney Lin' },
                    { date: '2020/07/04', assignee: 'Chloe Lin' },
                    { date: '2020/07/11', assignee: 'Vinnie Lin' },
                    { date: '2020/07/18', assignee: 'Qianwei Liu' },
                    { date: '2020/07/25', assignee: 'Xingru Wang' },
                    { date: '2020/08/01', assignee: 'Shaun Tung' },
                    { date: '2020/08/08', assignee: 'Shenney Lin' },
                    { date: '2020/08/15', assignee: 'Chloe Lin' },
                    { date: '2020/08/22', assignee: 'Vinnie Lin' },
                    { date: '2020/08/29', assignee: 'Qianwei Liu' },
                    { date: '2020/09/05', assignee: 'Xingru Wang' },
                    { date: '2020/09/12', assignee: 'Shaun Tung' },
                    { date: '2020/09/19', assignee: 'Shenney Lin' },
                ],
            },
            {
                title: 'Piano',
                role: 'Pianist',
                data: [
                    { date: '2020/06/27', assignee: 'Shouli Tung' },
                    { date: '2020/07/04', assignee: 'Shaun Tung' },
                    { date: '2020/07/11', assignee: 'Rebecca Lin' },
                    { date: '2020/07/18', assignee: 'Shenney Lin' },
                    { date: '2020/07/25', assignee: 'Joseph Wu' },
                    { date: '2020/08/01', assignee: 'Chloe Lin' },
                    { date: '2020/08/08', assignee: 'Vinnie Lin' },
                    { date: '2020/08/15', assignee: 'Shouli Tung' },
                    { date: '2020/08/22', assignee: 'Shaun Tung' },
                    { date: '2020/08/29', assignee: 'Rebecca Lin' },
                    { date: '2020/09/05', assignee: 'Shenney Lin' },
                    { date: '2020/09/12', assignee: 'Joseph Wu' },
                    { date: '2020/09/19', assignee: 'Chloe Lin' },
                ],
            },
        ],
    },
    {
        time: '2:00 PM',
        tasks: [
            {
                title: 'Sermon Speaker',
                role: 'Church Council',
                data: [
                    { date: '2020/06/27', assignee: 'Shouli Tung' },
                    { date: '2020/07/04', assignee: 'Shaun Tung' },
                    { date: '2020/07/11', assignee: 'Rebecca Lin' },
                    { date: '2020/07/18', assignee: 'Shenney Lin' },
                    { date: '2020/07/25', assignee: 'Joseph Wu' },
                    { date: '2020/08/01', assignee: 'Chloe Lin' },
                    { date: '2020/08/08', assignee: 'Vinnie Lin' },
                    { date: '2020/08/15', assignee: 'Shouli Tung' },
                    { date: '2020/08/22', assignee: 'Shaun Tung' },
                    { date: '2020/08/29', assignee: 'Rebecca Lin' },
                    { date: '2020/09/05', assignee: 'Shenney Lin' },
                    { date: '2020/09/12', assignee: 'Joseph Wu' },
                    { date: '2020/09/19', assignee: 'Chloe Lin' },
                ],
            },
            {
                title: 'Interpreter',
                role: 'Interpreter',
                data: [
                    { date: '2020/06/27', assignee: 'Joseph Wu' },
                    { date: '2020/07/04', assignee: 'Thomas Hsu' },
                    { date: '2020/07/11', assignee: 'Qianwei Liu' },
                    { date: '2020/07/18', assignee: 'Rebecca Lin' },
                    { date: '2020/07/25', assignee: 'Joseph Wu' },
                    { date: '2020/08/01', assignee: 'Thomas Hsu' },
                    { date: '2020/08/08', assignee: 'Qianwei Liu' },
                    { date: '2020/08/15', assignee: 'Rebecca Lin' },
                    { date: '2020/08/22', assignee: 'Joseph Wu' },
                    { date: '2020/08/29', assignee: 'Thomas Hsu' },
                    { date: '2020/09/05', assignee: 'Qianwei Liu' },
                    { date: '2020/09/12', assignee: 'Rebecca Lin' },
                    { date: '2020/09/19', assignee: 'Joseph Wu' },
                ],
            },
        ],
    },
];

// module.exports = events;
