export const events = [
  {
    serviceId: 1,
    roleId: 1,
    title: 'Usher',
    time: '10:15 AM',
    order: 1,
    displayTime: true,
  },
  {
    serviceId: 1,
    roleId: 2,
    title: 'Hymn Leading',
    time: '10:45 AM',
    order: 2,
    displayTime: true,
  },
  {
    serviceId: 1,
    roleId: 3,
    title: 'Piano',
    time: '10:45 AM',
    order: 3,
    displayTime: false,
  },
  {
    serviceId: 1,
    roleId: 1,
    title: 'Sermon Speaker',
    time: '11:00 AM',
    order: 4,
    displayTime: true,
  },
  {
    serviceId: 1,
    roleId: 4,
    title: 'Interpreter',
    time: '11:00 AM',
    order: 5,
    displayTime: false,
  },
  {
    serviceId: 1,
    roleId: 1,
    title: 'Announcer',
    time: '12:00 PM',
    order: 6,
    displayTime: true,
  },
  {
    serviceId: 1,
    roleId: 5,
    title: 'Grace',
    time: '12:00 PM',
    order: 7,
    displayTime: false,
  },
  {
    serviceId: 2,
    roleId: 2,
    title: 'Hymn Leading',
    time: '1:45 PM',
    order: 1,
    displayTime: true,
  },
  {
    serviceId: 2,
    roleId: 3,
    title: 'Piano',
    time: '1:45 PM',
    order: 2,
    displayTime: false,
  },
  {
    serviceId: 2,
    roleId: 1,
    title: 'Sermon Speaker',
    time: '2:00 PM',
    order: 3,
    displayTime: true,
  },
  {
    serviceId: 2,
    roleId: 4,
    title: 'Interpreter',
    time: '2:00 PM',
    order: 4,
    displayTime: false,
  },
  {
    serviceId: 3,
    roleId: 1,
    title: 'Usher',
    time: '7:00 PM',
    order: 1,
    displayTime: true,
  },
  {
    serviceId: 3,
    roleId: 2,
    title: 'Hymn Leading',
    time: '7:45 PM',
    order: 2,
    displayTime: true,
  },
  {
    serviceId: 3,
    roleId: 3,
    title: 'Piano',
    time: '7:45 PM',
    order: 3,
    displayTime: false,
  },
  {
    serviceId: 3,
    roleId: 1,
    title: 'Sermon Speaker',
    time: '8:00 PM',
    order: 4,
    displayTime: true,
  },
  {
    serviceId: 3,
    roleId: 4,
    title: 'Interpreter',
    time: '8:00 PM',
    order: 5,
    displayTime: false,
  },
];
