export const events = [
    {
        serviceId: 1,
        roleId: 1,
        day: 'Saturday',
        title: 'Usher',
        time: '10:15 AM',
        order: 1,
    },
    {
        serviceId: 1,
        roleId: 2,
        day: 'Saturday',
        title: 'Hymn Leading',
        time: '10:45 AM',
        order: 2,
    },
    {
        serviceId: 1,
        roleId: 3,
        day: 'Saturday',
        title: 'Piano',
        time: '10:45 AM',
        order: 3,
    },
    {
        serviceId: 1,
        roleId: 1,
        day: 'Saturday',
        title: 'Sermon Speaker',
        time: '11:00 AM',
        order: 4,
    },
    {
        serviceId: 1,
        roleId: 4,
        day: 'Saturday',
        title: 'Interpreter',
        time: '11:00 AM',
        order: 5,
    },
    {
        serviceId: 1,
        roleId: 1,
        day: 'Saturday',
        title: 'Announcer',
        time: '12:00 PM',
        order: 6,
    },
    {
        serviceId: 1,
        roleId: undefined,
        day: 'Saturday',
        title: 'Grace',
        time: '12:00 PM',
        order: 7,
    },
    {
        serviceId: 1,
        roleId: undefined,
        day: 'Saturday',
        title: 'Cooking',
        time: '12:00 PM',
        order: 8,
    },
    {
        serviceId: 2,
        roleId: 2,
        day: 'Saturday',
        title: 'Hymn Leading',
        time: '1:45 PM',
        order: 1,
    },
    {
        serviceId: 2,
        roleId: 3,
        day: 'Saturday',
        title: 'Piano',
        time: '1:45 PM',
        order: 2,
    },
    {
        serviceId: 2,
        roleId: 1,
        day: 'Saturday',
        title: 'Sermon Speaker',
        time: '2:00 PM',
        order: 3,
    },
    {
        serviceId: 2,
        roleId: 4,
        day: 'Saturday',
        title: 'Interpreter',
        time: '2:00 PM',
        order: 4,
    },
    {
        serviceId: 3,
        roleId: 1,
        day: 'Friday',
        title: 'Usher',
        time: '7:00 PM',
        order: 1,
    },
    {
        serviceId: 3,
        roleId: 2,
        day: 'Friday',
        title: 'Hymn Leading',
        time: '7:45 PM',
        order: 2,
    },
    {
        serviceId: 3,
        roleId: 3,
        day: 'Friday',
        title: 'Piano',
        time: '7:45 PM',
        order: 3,
    },
    {
        serviceId: 3,
        roleId: 1,
        day: 'Friday',
        title: 'Sermon Speaker',
        time: '8:00 PM',
        order: 4,
    },
    {
        serviceId: 3,
        roleId: 4,
        day: 'Friday',
        title: 'Interpreter',
        time: '8:00 PM',
        order: 5,
    },
];
