// eslint-disable-next-line import/prefer-default-export
export const users = [
    {
        firstName: 'Shaun',
        lastName: 'Tung',
        email: 'shaun.tung@gmail.com',
        password: 'password',
        isVerified: true,
        churchId: 1,
        expoPushToken: 'ExponentPushToken[-uuepvN27WLr5fHqJoK3y8]',
    },
    {
        firstName: 'Ted',
        lastName: 'Chen',
        email: 'ted.chen@gmail.com',
        password: 'password',
        isVerified: true,
        churchId: 1,
        expoPushToken: 'ExponentPushToken[F-BJ4-BkJXff6Lbp9SbI4K]',
    },
    {
        firstName: 'Jonathan',
        lastName: 'Lee',
        email: 'jonathan.lee@gmail.com',
        password: 'password',
        isVerified: true,
        churchId: 1,
        expoPushToken: 'ExponentPushToken[2CkbA5CQcxyiSNWT1oGvhC]',
    },
    // {
    //     firstName: 'Geoff',
    //     lastName: 'Chu',
    //     email: 'geoff.chu@gmail.com',
    //     password: 'password',
    //     isVerified: true,
    //     churchId: 1,
    // },
    // {
    //     firstName: 'Amanda',
    //     lastName: 'Chin',
    //     email: 'amanda.chin@gmail.com',
    //     password: 'password',
    //     isVerified: true,
    //     churchId: 1,
    // },
    // {
    //     firstName: 'Alan',
    //     lastName: 'Lin',
    //     email: 'alan.lin@gmail.com',
    //     password: 'password',
    //     isVerified: true,
    //     churchId: 1,
    // },
    // {
    //     firstName: 'Ian',
    //     lastName: 'Lin',
    //     email: 'ian.lin@gmail.com',
    //     password: 'password',
    //     isVerified: true,
    //     churchId: 2,
    // },
];
