// eslint-disable-next-line import/prefer-default-export
export const users = [
    {
        firstName: 'Shaun',
        lastName: 'Tung',
        email: 'shaun.tung@gmail.com',
        password: 'password',
        isVerified: true,
        churchId: 2,
        expoPushToken: 'ExponentPushToken[-uuepvN27WLr5fHqJoK3y8]',
    },
    {
        firstName: 'Sun-Yu',
        lastName: 'Yang',
        email: 'sun-yu.yang@gmail.com',
        password: 'password1',
        isVerified: true,
        churchId: 2,
        expoPushToken: 'ExponentPushToken[-uuepvN27WLr5fHqJoK3y8]',
    },
    {
        firstName: 'Kevin',
        lastName: 'Wang',
        email: 'kevin.wang@gmail.com',
        password: 'password2',
        isVerified: true,
        churchId: 2,
        expoPushToken: 'ExponentPushToken[-uuepvN27WLr5fHqJoK3y8]',
    },
    {
        firstName: 'Yvonne',
        lastName: 'Wong',
        email: 'yvonne.wong@gmail.com',
        password: 'password3',
        isVerified: true,
        churchId: 2,
        expoPushToken: 'ExponentPushToken[-uuepvN27WLr5fHqJoK3y8]',
    },
    {
        firstName: 'Shouli',
        lastName: 'Tung',
        email: 'shouli.tung@gmail.com',
        password: 'password4',
        isVerified: true,
        churchId: 2,
        expoPushToken: 'ExponentPushToken[-uuepvN27WLr5fHqJoK3y8]',
    },
    {
        firstName: 'Rebecca',
        lastName: 'Lin',
        email: 'rebecca.lin@gmail.com',
        password: 'password5',
        isVerified: true,
        churchId: 2,
        expoPushToken: 'ExponentPushToken[-uuepvN27WLr5fHqJoK3y8]',
    },
    {
        firstName: 'Shenney',
        lastName: 'Lin',
        email: 'shenney.lin@gmail.com',
        password: 'password6',
        isVerified: true,
        churchId: 2,
        expoPushToken: 'ExponentPushToken[-uuepvN27WLr5fHqJoK3y8]',
    },
    {
        firstName: 'Joseph',
        lastName: 'Wu',
        email: 'joseph.wu@gmail.com',
        password: 'password7',
        isVerified: true,
        churchId: 2,
        expoPushToken: 'ExponentPushToken[-uuepvN27WLr5fHqJoK3y8]',
    },
    {
        firstName: 'Brenda',
        lastName: 'Ong',
        email: 'brenda.ong@gmail.com',
        password: 'password8',
        isVerified: true,
        churchId: 2,
        expoPushToken: 'ExponentPushToken[-uuepvN27WLr5fHqJoK3y8]',
    },
    {
        firstName: 'Thomas',
        lastName: 'Hsu',
        email: 'thomas.hsu@gmail.com',
        password: 'password9',
        isVerified: true,
        churchId: 2,
        expoPushToken: 'ExponentPushToken[-uuepvN27WLr5fHqJoK3y8]',
    },
    {
        firstName: 'Qianwei',
        lastName: 'Liu',
        email: 'qianwei.liu@gmail.com',
        password: 'password10',
        isVerified: true,
        churchId: 2,
        expoPushToken: 'ExponentPushToken[-uuepvN27WLr5fHqJoK3y8]',
    },
    {
        firstName: 'Chloe',
        lastName: 'Lin',
        email: 'chloe.lin@gmail.com',
        password: 'password11',
        isVerified: true,
        churchId: 2,
        expoPushToken: 'ExponentPushToken[-uuepvN27WLr5fHqJoK3y8]',
    },
    {
        firstName: 'Vinnie',
        lastName: 'Lin',
        email: 'vinnie.lin@gmail.com',
        password: 'password12',
        isVerified: true,
        churchId: 2,
        expoPushToken: 'ExponentPushToken[-uuepvN27WLr5fHqJoK3y8]',
    },
    {
        firstName: 'Xing-ru',
        lastName: 'Wang',
        email: 'xingru.wang@gmail.com',
        password: 'password13',
        isVerified: true,
        churchId: 2,
        expoPushToken: 'ExponentPushToken[-uuepvN27WLr5fHqJoK3y8]',
    },
];
